DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS comment;

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  image TEXT NOT NULL,
  votes INTEGER DEFAULT 0
);

create TABLE comment (
    id INTEGER,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    comment TEXT NOT NULL
);